In [1]:
%pip install numpy
import numpy as np

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)
print(a-b)
print(a/b)
print(a//b)
print(a*b)
print(a**b)
print(a%b)

[5 7 9]
[-3 -3 -3]
[0.25 0.4  0.5 ]
[0 0 0]
[ 4 10 18]
[  1  32 729]
[1 2 3]


In [4]:
c=np.array([[1,2,3],[2,3,4]])
d=np.array([[1,2,3],[4,5,6]])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)
print(a**b)
np.dot(a,np.transpose(b))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 0 0]
[1 2 3]
[  1  32 729]


np.int64(32)

In [5]:
a = np.array([[10,20,30],[5,10,15]])

print(np.min(a))
print(np.sum(a))
print(np.max(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

5
90
30
[15 30 45]
[60 30]
